<body class="body-singup" >

    <main class="main-singup">
        <div class="row d-flex justify-content-center main-singup">

            <div class="col-md-12 ml-auto mr-auto">
                <div class="row justify-content-center">

                    <div class="container m-top-150 m-bottom">
                        <h1 class="title">Políticas de Privacidad</h1>
                        <h2>1. &#65279;POLÍTICAS DE PRIVACIDAD</h2>
                        <p>1.1. La presente Política de Privacidad (en adelante la “Política de Privacidad”) se integra con los Términos y Condiciones disponibles en <a href="http://www.ventasnube.com/terminos-de-uso">www.ventasnube.com/terminos-de-uso</a> y se aplicarán a los Usuarios del Sitio, estén o no debidamente registrados. Las definiciones utilizadas en los Términos y Condiciones subsistirán y serán aplicable en las presente Políticas de Privacidad.</p>
                        <p>1.2. La Empresa podrá modificar la Política de Privacidad en cualquier momento. Las nuevas versiones de la Política de Privacidad serán notificadas previamente a su entrada en vigencia mediante: (i) publicación de dicha nueva versión en <a href="http://www.ventasnube.com/tienda/privacy">www.ventasnube.com/tienda/privacy</a>, y/o (ii) por mensaje de correo electrónico dirigido al Usuario con un enlace a <a href="http://www.ventasnube.com/tienda/privacy">www.ventasnube.com/tienda/privacy</a>.</p>
                        <p>1.3. El Usuario acepta que será dado por notificado de cualquier modificación a la Política de Privacidad una vez que la Empresa hubiera publicado las mismas en <a href="http://www.ventasnube.com/privacy">www.ventasnube.com/tienda/privacy</a>, y que la continuación del Usuario en el uso de los Servicios una vez publicada dicha nueva versión se considerará como aceptación de dichas modificaciones a la Política de Privacidad. En consecuencia, el Usuario acepta: (i) chequear <a href="http://www.ventasnube.com/tienda/privacy">www.ventasnube.com/tienda/privacy</a> periódicamente; y (ii) leer cualquier mensaje de correo electrónico que sea enviado por la Empresa con cualquier modificación o nueva versión.</p>
                        <h2>2. RECOLECCIÓN DE INFORMACIÓN DE LOS USUARIOS</h2>
                        <p>2.1. El Usuario reconoce y acepta que la Empresa pueda recolectar información acerca de los Usuarios al momento de registrarse en el Sitio, tales como su nombre, apellido y correo electrónico, como así también de aquellas personas que escriban a <a href="mailto:hola@ventasnube.com">hola@ventasnube.com</a> o que completen nuestras encuestas en el Sitio (en adelante los “Datos”). Los Datos serán almacenados en una base de datos de propiedad de la Empresa y será tratada en forma confidencial y con los debidas medidas de seguridad que se detallarán más adelante.</p>
                        <p>2.2. La Empresa no almacenará ni recopilará la información y datos de los medios de pago de los Usuarios como ser los números de las tarjetas de crédito o cuentas bancarias, etc. Dicha información será almacenada y/o recopilada por Gateways de pago externos provistos por otras compañías, de acuerdo a lo establecido en los Términos y Condiciones, no teniendo la Empresa acceso a la misma o a dichos servidores en donde se encuentran almacenados. En tal sentido, la Empresa no se hace responsable de ningún daño o perjuicio que pueda ocurrir al momento de realizar pagos o transacciones a través de dichos proveedores.</p>
                        <h2>3. FINALIDAD DE LOS DATOS</h2>
                        <p>3.1 Los Datos suministrados por el Usuario y recolectados de conformidad con lo establecido en las presentes Políticas de Privacidad serán utilizados con la siguiente finalidad:</p>
                        <ol>
                            <li>Identificación del Usuario;</li>
                            <li>Facturación y cobro del servicio contratado;</li>
                            <li>Posibilidad de dar acceso al Servicio;</li>
                            <li>Poder contar con un teléfono o dirección de correo electrónico para contactarse con el Usuario con motivo de la utilización de los Servicios;</li>
                            <li>Envío de información promocional de productos o servicios de la Empresa, a través del envío de Newsletters. En dicho caso, si el Usuario lo deseara, podrá solicitar que se lo elimine de las listas para el envío de información promocional o publicitaria;</li>
                        </ol>
                        <p>3.2. Adicionalmente, la información que provea el Usuario y que la Empresa recolecte directamente en nombre de dicho Usuario, podrá ser utilizada por la Empresa para el intercambio de datos entre clientes del Usuario y otros Usuarios a los fines de brindar los Servicios con una mayor eficacia.</p>
                        <p>3.3. Como parte del proceso de venta a través de la Tienda, los Usuarios recibirán información de sus clientes. Al registrarse en el Sitio y aceptar los Términos y Condiciones, los Usuarios estarán prestando su consentimiento expreso para que la información brindada por la Empresa a los Usuarios sea únicamente utilizada con el fin de ofrecer sus productos o servicios a sus clientes y a otros Usuarios.</p>
                        <p>3.4. La Empresa podrá compartir la información con otras empresas de servicios o sitios de internet dedicados a la evaluación de las conductas de los Usuarios de internet o similares a los fines de mejorar la calidad de los servicios de la Empresa. Generalmente dichas empresas o sitios de internet poseen sus propias políticas de privacidad de datos a los fines de su protección. De todas maneras la Empresa empeñará sus mejores esfuerzos en que la privacidad de la información compartida sea protegida de la mejor manera posible. Sin perjuicio de ello, la Empresa no será responsable por los daños provocados por tales empresas y/o sitios de internet en cuanto a su deber de protección, confidencialidad y privacidad de los datos que ellas manejan. Cada uno de estos servicios de terceros cuentan con sus propias políticas de privacidad y proveen, en los casos que se encuentre disponible, un método con el que Usuario podrá hacer un opt-out; entre ellos:</p>
                        <ol>
                            <li><a href="http://www.google.com/privacy.html">http://www.google.com/privacy.html</a></li>
                            <li><a href="http://info.yahoo.com/privacy/us/biz/rightmedia/details.html">http://info.yahoo.com/privacy/us/biz/rightmedia/details.html</a></li>
                            <li><a href="http://www.assistly.com/privacy">http://www.assistly.com/privacy</a></li>
                            <li><a href="http://highrisehq.com/privacy">http://highrisehq.com/privacy</a></li>
                            <li><a href="http://mailchimp.com/legal/privacy/">http://mailchimp.com/legal/privacy/</a></li>
                            <li><a href="https://cms.paypal.com/ar/cgi-bin/marketingweb?cmd=_render-content&amp;content_ID=ua/Privacy_full&amp;locale.x=es_XC">https://cms.paypal.com/ar/cgi-bin/marketingweb?cmd=<em>render-content&amp;content</em>ID=ua/Privacy<em>full&amp;locale.x=es</em>XC</a></li>
                        </ol>
                        <p>3.5. La Empresa utilizará los Datos provistos por el Usuario, y la recolectada por la Empresa conforme a lo establecido en las Políticas de Privacidad, y no la divulgará salvo que sea solicitada por tribunales, u organismos estatales nacionales o internacionales que así lo requieran y lo soliciten en la forma correspondiente.</p>
                        <p>3.6. La Empresa no estará obligado a retener la información durante ningún plazo establecido y dispondrá la eliminación de la misma cuando lo juzgue conveniente.</p>
                        <p>3.7. La Empresa podrá contener enlaces a otros sitios de internet que no sean propiedad de la Empresa. En consecuencia la Empresa no será responsable por el actuar de dichos sitios de internet, a los cuales no se aplicará la presente Política de Privacidad. Recomendamos examinar la política de privacidad detallada en aquellos sitios de internet para entender los procedimientos de recolección de información que utilizan y como protegen sus datos personales.</p>
                        <p>3.8. La Empresa es propietaria de todas las bases de datos y dispositivos de almacenamiento, así como también del software que desarrolla. Sin embargo, la Empresa no es dueña de la información que los Usuarios almacenan en su Sitio y/o que reciben como parte de sus ventas. Los Usuarios tienen todos los derechos sobre dicha información.</p>
                        <h2>4. MENORES DE EDAD</h2>
                        <p>4.1 El Sitio y/o los Servicios están permitidos sólo a quienes tengan edad legal para contratar y no se encuentren inhibidos legalmente o de algún modo vedados de ejercer actos jurídicos, derechos y/u obligaciones. Habida cuenta de ello, los menores de 18 años no tienen permitido el ingreso al Sitio y/o los Servicios ni el suministro de ningún dato personal u otro tipo de información.</p>
                        <h2>5. CONFIDENCIALIDAD Y SEGURIDAD DE LA INFORMACIÓN</h2>
                        <p>5.1. La Empresa ha adoptado medidas de seguridad razonables para proteger la información de los Usuarios, e impedir el acceso no autorizado a sus datos o cualquier modificación, divulgación o destrucción no autorizada de los mismos. La información recolectada por la Empresa será mantenida de manera estrictamente confidencial. El acceso a los datos personales está restringido a aquellos empleados, contratistas y representantes de la Empresa que necesitan conocer tales datos para desempeñar sus funciones y desarrollar o mejorar nuestros servicios. La Empresa exige a sus proveedores los mismos estándares de confidencialidad. La Empresa no permite el acceso a esta información a terceros ajenos a la Empresa, a excepción de un pedido expreso del Usuario.</p>
                        <p>5.2. La seguridad de los datos de los Usuarios es importante para la Empresa. El software utilizado por la Empresa para proteger los datos brindados por los Usuarios y la información recabada por la Empresa es protocolo SSL con claves de 256 bits para encriptar las comunicaciones y encriptación bcrypt para almacenar las contraseñar en la base de datos.</p>
                        <h2>6. CESION DE LOS DATOS</h2>
                        <p>La Empresa no venderá, alquilará ni compartirá los Datos de los Usuarios salvo aquellos casos expresamente previstos en las Políticas de Privacidad. No obstante ello, el Usuario presta su expresa conformidad para que la Empresa transfiera total o parcialmente los datos del Usuario a cualquiera de sus sociedades controladas, controlantes y/o vinculadas con la Empresa.</p>
                        <h2>7. COOKIES</h2>
                        <p>7.1. El Usuario reconoce y acepta que el Sitio podrá utilizar cookies para brindar a los Usuarios un servicio más completo, recordando sus preferencias. La información que recopile la Empresa podrá incluir el comportamiento de navegación, dirección IP, logs, y otros tipos de información. Sin embargo, la Empresa no recolectará información personal identificable de manera directa de ningún Usuario usando cookies o tags. Un cookie es un pequeño archivo de texto mediante el cual se puede identificar en forma exclusiva un navegador de internet, y que suele ser instalado, enviado o escrito en el ordenador de los Usuarios de internet, cuando los mismos ingresan a determinados sitios de internet, a efectos de obtener automáticamente información acerca de la conducta de los Usuarios cuando navegan por dichos sitios de internet. Un archivo cookie generalmente contendrá el nombre del dominio desde donde la cookie ha sido transferida, la fecha de creación, y un código de identificación. La única información personal que un cookie puede contener es información que el Usuario mismo suministra con su navegación por internet, tales como la dirección de IP, las páginas visitadas y en qué orden, el tiempo de permanencia en cada página, la fecha y la hora, etc. (la “Información de Actividad”). Un cookie no puede leer datos del disco duro del Usuario ni leer los archivos cookie creados por otros sitios de internet.</p>
                        <p>7.2. La mayoría de los navegadores están configurados para aceptar cookies, pero los Usuarios podrán reconfigurar su navegador de internet para rechazar todas las cookies o para que el sistema le indique en qué momento se envía una. Sin embargo, si las cookies están inhabilitadas, es posible que algunas características y servicios de los sitios de internet no funcionen de manera adecuada.</p>
                        <p>7.3. Los Usuarios podrán optar por que su navegador de internet no sea identificado por los Servicios. En tal caso, el Usuario deberá acudir a la sección de ayuda de su navegador.</p>
                        <p>7.4. La empresa hace uso de características de Google Analytics tales como remarketing o los informes de impresiones de la Red de Display de Google, pero no limitadas a éstas. Los visitantes pueden inhabilitar Google Analytics para la publicidad de display y personalizar los anuncios de la Red de Display de Google mediante la <a href="https://www.google.com/settings/ads">Configuración de anuncios</a>. El usuario también puede hacer uso del <a href="https://tools.google.com/dlpage/gaoptout/">complemento de inhabilitación para navegadores de Google Analytics</a>.</p>
                        <p>7.5. La empresa utiliza la función de remarketing con Google Analytics para publicar anuncios online. Otros proveedores, incluido Google, muestran sus anuncios en sitios de Internet. La empresa y otros proveedores, incluido Google, usan las cookies de origen (como la cookie de Google Analytics) y las cookies de terceros (como la cookie de DoubleClick) combinadas para informar, optimizar y publicar anuncios basándose en las visitas anteriores al sitio web.</p>
                        <p>7.6. La empresa y otros proveedores, incluido Google, usan las cookies de origen (como la cookie de Google Analytics) y las cookies de terceros (como la cookie de DoubleClick) combinadas para informar sobre cómo se relacionan con las visitas al sitio las impresiones de los anuncios, otros usos de los servicios publicitarios y las interacciones con estas impresiones de los anuncios y servicios publicitarios.</p>
                        <h2>8. DERECHO AL ACCESO, CANCELACION Y RECTIFICACION DE LOS DATOS</h2>
                        <p>8.1. Los usuarios tendrán derecho a hacer uso responsable de su cuenta en el sitio web. En cualquier momento, el Usuario podrá solicitar la baja como Usuario y la eliminación de su cuenta e información de la base de datos de la Empresa, como así también acceder y actualizar a sus datos personales. Para aquellos Usuarios residentes en Argentina, el titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326 de la Republica Argentina. La autoridad de aplicación (en Argentina, la Dirección Nacional de Protección de Datos Personales, Órgano de Control de la Ley Nº 25.326), tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las Normas sobre protección de datos personales.</p>
                        <p>8.2. A dichos efectos, el Usuario deberá enviar su Solicitud mediante el envío de un correo electrónico con el asunto “Acceso a Datos Personales” a <a href="mailto:hola@ventasnube.com">hola@ventasnube.com</a>. La Empresa podrá requerir a dicho Usuario que se identifique, lo que podrá ser verificado por la Empresa, así como que precise los datos personales a los cuales desean acceder, rectificar o remover.</p>
                        <h2>9. CONTACTO</h2>
                        <p>9.1. En caso que el Usuario tenga alguna duda acerca de la Política de Privacidad, o sobre la aplicación de la misma, deberá ponerse en contacto con la Empresa, en cualquier momento, vía correo electrónico a <a href="mailto:hola@ventasnube.com">hola@ventasnube.com</a>.
                            LINKEDSTORE S.R.L., C.U.I.T. N° 30-71201935-9, CON DOMICILIO EN Guatemala 5455, Piso 5, CIUDAD AUTÓNOMA DE BUENOS AIRES, ARGENTINA.</p>
                    </div>


                </div>


            </div>

        </div>
        </div>
    </main>

</body>

<!-- Section: Block Content -->
<!-- Footer -->